region: "us-west-2"

APNS_BASE_ARN: ${ssm:/DR/services/sns-apns-development}
GCM_BASE_ARN: ${ssm:/DR/services/sns-gcm-development}

KMS_KEY: ${ssm:/DR/security/default-kms-key}
ELASTICACHE_CONFIGURATION_ENDPOINT: ${ssm:/DR/services/memcached/connection-url}
MEMCACHED_DEFAULT_TTL_VALUE: "604800"
